services:
  mongodb:
    image: mongo:7.0
    container_name: codelens_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=codelensai
    volumes:
      - mongo_data:/data/db
    networks:
      - codelens-network

  redis:
    image: redis:7-alpine
    container_name: codelens_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - codelens-network

volumes:
  mongo_data:
    driver: local
  redis_data:
    driver: local

networks:
  codelens-network:
    driver: bridge
